# Generated by Django 5.2.8 on 2025-12-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('helper', 'Helper')], default='user', max_length=10),
        ),
    ]
