# Generated by Django 5.2.8 on 2025-12-01 09:22

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customauth', '0003_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, help_text='List of required service slugs', size=None)),
                ('city', models.CharField(max_length=128)),
                ('area', models.CharField(blank=True, max_length=128)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('frequency', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_prefs', to='customauth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='customauth.user')),
            ],
        ),
        migrations.CreateModel(
            name='HelperProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, help_text='List of services (slugs) this helper can provide', size=None)),
                ('city', models.CharField(max_length=128)),
                ('area', models.CharField(blank=True, max_length=128)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('frequency_modes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, help_text='Acceptable frequencies: "one_time", "weekly", "monthly"', size=None)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_profile', to='customauth.user')),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'active'], name='userprofile_city_b42d14_idx')],
            },
        ),
    ]
